cloud:
  aws:
    credentials:
      access-key: AKIAIGXNJIZSA3OQBWCQ
      secret-key: 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
    region:
      static: sa-east-1
    stack:
      auto: false

application:
  bucket:
    name: ad-generator-jp


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
